#!/usr/bin/env python
#encoding=utf-8

import os
import sys 
import traceback
import unittest
from HTMLTestRunner import HTMLTestRunner

import webbrowser


class test_raise(unittest.TestCase):
    def setUp(self):
        pass

    def test01(self):
        try:
            print 2/0
        except Exception,e:
            #这里用的是：print e.message，观察test01的测试报告
            print e.message
        else:
            print 'test01-else'
        finally:
            print 'test01-finally'

    def test02(self):
        try:
            print 2/0
        except Exception,e:
            #这里用的是 ：raise e，观察test02的测试报告
            raise e
        else:
            print 'test02-else'
        finally:
            print 'test02-finally'

    def tearDown(self):
        pass

if __name__=='__main__':
    suite=unittest.TestSuite()
    suite.addTests([test_raise('test01'),test_raise('test02')])

    report_path = os.path.join(os.getcwd(),"report.html")

    with open(report_path,'w+')as fp:
        runner=HTMLTestRunner(stream=fp,title='raise e and print e',description='Generated by HTMLTestRunner.',verbosity=2)
        runner.run(suite)


    GEN_HTML = report_path
    #运行完自动在网页中显示
    webbrowser.open(GEN_HTML,new = 1)

